version: '3.8'

volumes:
  jira_sync_logs:

services:
  mirror:
    build: .
    volumes:
      - jira_sync_logs:/app/logs:rw
    env_file:
      - stack.env
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/app/logs/sync.log"]
      interval: 5m
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development service for testing
  mirror-dev:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env.example
    profiles:
      - dev
    command: ["--no-schedule"]  # Run once for testing
